---
title: "ice_model_output_comparisons"
output: html_document
date: "2026-05-01"
---

```{r}

```



```{r}
inputs      <- prepare_elb_model_inputs(BOYM, HOEM, COHM, TARM,
                                        airt_elb, airt_wlb,
                                        ice_raw, albedo_raw)

prepped_obs <- prepare_model_input(inputs$time_series, warming_rate = 0.000)
results_obs <- run_ice_model(prepped_obs)
```

```{r}
# ---- Scenario pathway ----
clim_scenario  <- build_climate_scenario(
  airt_elb = airt_elb,
  airt_wlb = airt_wlb,
  albedo_df = albedo_raw,
  year_start = 2020,
  year_end   = 2050,
  flat_offsets = list(air_temp = 0.0, wind = 1.5),
  seasonal_adjustments = list(
    air_temp = c(summer = 0, autumn = 0, winter = 0, spring = 0),
    sw_in    = c(summer = 0,  autumn = 0,   winter = 0,   spring = 0)
  )
)
prepped_scen  <- prepare_model_input(clim_scenario, warming_rate = 0.000)
results_scen  <- run_ice_model(prepped_scen)

```


```{r}
plot_scenario(prepped_obs)
plot_ice_model(results_obs,  ice_thickness = inputs$ice_thickness)

```

```{r}
plot_scenario(clim_scenario)
plot_ice_model(results_scen)
```

